[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.1"

[features]
seeds = false

[programs.localnet]
iam_voter_weight = "99nwXzcugse3x8kxE9v6mxZiq8T9gHDoznaaG6qcw534"

[programs.devnet]
iam_voter_weight = "99nwXzcugse3x8kxE9v6mxZiq8T9gHDoznaaG6qcw534"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../.config/devnet-authority.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "GZYwTp2ozeuRA5Gof9vs4ya961aANcJBdUzB7LN6q4b2"
program = "tests/fixtures/iam_anchor.so"

[[test.genesis]]
address = "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"
program = "tests/fixtures/spl_governance.so"

[[test.validator.account]]
address = "63cKuvoe9WuNH9Ds6aXF7iSc4jHmJc4ZkxdHTaitJ5tr"
filename = "tests/fixtures/identity-state-a.json"

[[test.validator.account]]
address = "73gAPp8WuNzdHh4E5ySQNFR3jpw8qs5YFaYPp8iyt6FZ"
filename = "tests/fixtures/identity-state-b.json"
